# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@biomejs/biome@2.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/biome/-/biome-2.3.13.tgz";
    hash = "sha512-Fw7UsV0UAtWIBIm0M7g5CRerpu1eKyKAXIazzxhbXYUyMkwNrkX/KLkGI7b+uVDQ5cLUMfOC9vR60q9IDYDstA==";
  };
  "@biomejs/cli-darwin-arm64@2.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-darwin-arm64/-/cli-darwin-arm64-2.3.13.tgz";
    hash = "sha512-0OCwP0/BoKzyJHnFdaTk/i7hIP9JHH9oJJq6hrSCPmJPo8JWcJhprK4gQlhFzrwdTBAW4Bjt/RmCf3ZZe59gwQ==";
  };
  "@biomejs/cli-darwin-x64@2.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-darwin-x64/-/cli-darwin-x64-2.3.13.tgz";
    hash = "sha512-AGr8OoemT/ejynbIu56qeil2+F2WLkIjn2d8jGK1JkchxnMUhYOfnqc9sVzcRxpG9Ycvw4weQ5sprRvtb7Yhcw==";
  };
  "@biomejs/cli-linux-arm64-musl@2.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-linux-arm64-musl/-/cli-linux-arm64-musl-2.3.13.tgz";
    hash = "sha512-TUdDCSY+Eo/EHjhJz7P2GnWwfqet+lFxBZzGHldrvULr59AgahamLs/N85SC4+bdF86EhqDuuw9rYLvLFWWlXA==";
  };
  "@biomejs/cli-linux-arm64@2.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-linux-arm64/-/cli-linux-arm64-2.3.13.tgz";
    hash = "sha512-xvOiFkrDNu607MPMBUQ6huHmBG1PZLOrqhtK6pXJW3GjfVqJg0Z/qpTdhXfcqWdSZHcT+Nct2fOgewZvytESkw==";
  };
  "@biomejs/cli-linux-x64-musl@2.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-linux-x64-musl/-/cli-linux-x64-musl-2.3.13.tgz";
    hash = "sha512-0bdwFVSbbM//Sds6OjtnmQGp4eUjOTt6kHvR/1P0ieR9GcTUAlPNvPC3DiavTqq302W34Ae2T6u5VVNGuQtGlQ==";
  };
  "@biomejs/cli-linux-x64@2.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-linux-x64/-/cli-linux-x64-2.3.13.tgz";
    hash = "sha512-s+YsZlgiXNq8XkgHs6xdvKDFOj/bwTEevqEY6rC2I3cBHbxXYU1LOZstH3Ffw9hE5tE1sqT7U23C00MzkXztMw==";
  };
  "@biomejs/cli-win32-arm64@2.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-win32-arm64/-/cli-win32-arm64-2.3.13.tgz";
    hash = "sha512-QweDxY89fq0VvrxME+wS/BXKmqMrOTZlN9SqQ79kQSIc3FrEwvW/PvUegQF6XIVaekncDykB5dzPqjbwSKs9DA==";
  };
  "@biomejs/cli-win32-x64@2.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@biomejs/cli-win32-x64/-/cli-win32-x64-2.3.13.tgz";
    hash = "sha512-trDw2ogdM2lyav9WFQsdsfdVy1dvZALymRpgmWsvSez0BJzBjulhOT/t+wyKeh3pZWvwP3VMs1SoOKwO3wecMQ==";
  };
  "@resvg/resvg-js-android-arm-eabi@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-android-arm-eabi/-/resvg-js-android-arm-eabi-2.6.2.tgz";
    hash = "sha512-FrJibrAk6v29eabIPgcTUMPXiEz8ssrAk7TXxsiZzww9UTQ1Z5KAbFJs+Z0Ez+VZTYgnE5IQJqBcoSiMebtPHA==";
  };
  "@resvg/resvg-js-android-arm64@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-android-arm64/-/resvg-js-android-arm64-2.6.2.tgz";
    hash = "sha512-VcOKezEhm2VqzXpcIJoITuvUS/fcjIw5NA/w3tjzWyzmvoCdd+QXIqy3FBGulWdClvp4g+IfUemigrkLThSjAQ==";
  };
  "@resvg/resvg-js-darwin-arm64@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-darwin-arm64/-/resvg-js-darwin-arm64-2.6.2.tgz";
    hash = "sha512-nmok2LnAd6nLUKI16aEB9ydMC6Lidiiq2m1nEBDR1LaaP7FGs4AJ90qDraxX+CWlVuRlvNjyYJTNv8qFjtL9+A==";
  };
  "@resvg/resvg-js-darwin-x64@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-darwin-x64/-/resvg-js-darwin-x64-2.6.2.tgz";
    hash = "sha512-GInyZLjgWDfsVT6+SHxQVRwNzV0AuA1uqGsOAW+0th56J7Nh6bHHKXHBWzUrihxMetcFDmQMAX1tZ1fZDYSRsw==";
  };
  "@resvg/resvg-js-linux-arm-gnueabihf@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-linux-arm-gnueabihf/-/resvg-js-linux-arm-gnueabihf-2.6.2.tgz";
    hash = "sha512-YIV3u/R9zJbpqTTNwTZM5/ocWetDKGsro0SWp70eGEM9eV2MerWyBRZnQIgzU3YBnSBQ1RcxRZvY/UxwESfZIw==";
  };
  "@resvg/resvg-js-linux-arm64-gnu@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-linux-arm64-gnu/-/resvg-js-linux-arm64-gnu-2.6.2.tgz";
    hash = "sha512-zc2BlJSim7YR4FZDQ8OUoJg5holYzdiYMeobb9pJuGDidGL9KZUv7SbiD4E8oZogtYY42UZEap7dqkkYuA91pg==";
  };
  "@resvg/resvg-js-linux-arm64-musl@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-linux-arm64-musl/-/resvg-js-linux-arm64-musl-2.6.2.tgz";
    hash = "sha512-3h3dLPWNgSsD4lQBJPb4f+kvdOSJHa5PjTYVsWHxLUzH4IFTJUAnmuWpw4KqyQ3NA5QCyhw4TWgxk3jRkQxEKg==";
  };
  "@resvg/resvg-js-linux-x64-gnu@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-linux-x64-gnu/-/resvg-js-linux-x64-gnu-2.6.2.tgz";
    hash = "sha512-IVUe+ckIerA7xMZ50duAZzwf1U7khQe2E0QpUxu5MBJNao5RqC0zwV/Zm965vw6D3gGFUl7j4m+oJjubBVoftw==";
  };
  "@resvg/resvg-js-linux-x64-musl@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-linux-x64-musl/-/resvg-js-linux-x64-musl-2.6.2.tgz";
    hash = "sha512-UOf83vqTzoYQO9SZ0fPl2ZIFtNIz/Rr/y+7X8XRX1ZnBYsQ/tTb+cj9TE+KHOdmlTFBxhYzVkP2lRByCzqi4jQ==";
  };
  "@resvg/resvg-js-win32-arm64-msvc@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-win32-arm64-msvc/-/resvg-js-win32-arm64-msvc-2.6.2.tgz";
    hash = "sha512-7C/RSgCa+7vqZ7qAbItfiaAWhyRSoD4l4BQAbVDqRRsRgY+S+hgS3in0Rxr7IorKUpGE69X48q6/nOAuTJQxeQ==";
  };
  "@resvg/resvg-js-win32-ia32-msvc@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-win32-ia32-msvc/-/resvg-js-win32-ia32-msvc-2.6.2.tgz";
    hash = "sha512-har4aPAlvjnLcil40AC77YDIk6loMawuJwFINEM7n0pZviwMkMvjb2W5ZirsNOZY4aDbo5tLx0wNMREp5Brk+w==";
  };
  "@resvg/resvg-js-win32-x64-msvc@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js-win32-x64-msvc/-/resvg-js-win32-x64-msvc-2.6.2.tgz";
    hash = "sha512-ZXtYhtUr5SSaBrUDq7DiyjOFJqBVL/dOBN7N/qmi/pO0IgiWW/f/ue3nbvu9joWE5aAKDoIzy/CxsY0suwGosQ==";
  };
  "@resvg/resvg-js@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/@resvg/resvg-js/-/resvg-js-2.6.2.tgz";
    hash = "sha512-xBaJish5OeGmniDj9cW5PRa/PtmuVU3ziqrbr5xJj901ZDN4TosrVaNZpEiLZAxdfnhAe7uQ7QFWfjPe9d9K2Q==";
  };
  "@types/bun@1.3.8" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.3.8.tgz";
    hash = "sha512-3LvWJ2q5GerAXYxO2mffLTqOzEu5qnhEAlh48Vnu8WQfnmSwbgagjGZV6BoHKJztENYEDn6QmVd949W4uESRJA==";
  };
  "@types/node@25.0.10" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-25.0.10.tgz";
    hash = "sha512-zWW5KPngR/yvakJgGOmZ5vTBemDoSqF3AcV/LrO5u5wTWyEAVVh+IT39G4gtyAkh3CtTZs8aX/yRM82OfzHJRg==";
  };
  "@types/pngjs@6.0.5" = fetchurl {
    url = "https://registry.npmjs.org/@types/pngjs/-/pngjs-6.0.5.tgz";
    hash = "sha512-0k5eKfrA83JOZPppLtS2C7OUtyNAl2wKNxfyYl9Q5g9lPkgBl/9hNyAu6HuEH2J4XmIv2znEpkDd0SaZVxW6iQ==";
  };
  "argparse@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
    hash = "sha512-8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
  };
  "base64-js@1.5.1" = fetchurl {
    url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
    hash = "sha512-AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
  };
  "bl@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/bl/-/bl-4.1.0.tgz";
    hash = "sha512-1W07cM9gS6DcLperZfFSj+bWLtaPGSOHWhPiGzXmvVJbRLdG82sH/Kn8EtW1VqWVA54AKf2h5k5BbnIbwF3h6w==";
  };
  "buffer@5.7.1" = fetchurl {
    url = "https://registry.npmjs.org/buffer/-/buffer-5.7.1.tgz";
    hash = "sha512-EHcyIPBQ4BSGlvjB16k5KgAJ27CIsHY/2JBmCRReo48y9rQ3MaUzWX3KVlBa4U7MyX02HdVj0K7C3WaB3ju7FQ==";
  };
  "bun-types@1.3.8" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.3.8.tgz";
    hash = "sha512-fL99nxdOWvV4LqjmC+8Q9kW3M4QTtTR1eePs94v5ctGqU8OeceWrSUaRw3JYb7tU3FkMIAjkueehrHPPPGKi5Q==";
  };
  "canvas@3.2.1" = fetchurl {
    url = "https://registry.npmjs.org/canvas/-/canvas-3.2.1.tgz";
    hash = "sha512-ej1sPFR5+0YWtaVp6S1N1FVz69TQCqmrkGeRvQxZeAB1nAIcjNTHVwrZtYtWFFBmQsF40/uDLehsW5KuYC99mg==";
  };
  "chownr@1.1.4" = fetchurl {
    url = "https://registry.npmjs.org/chownr/-/chownr-1.1.4.tgz";
    hash = "sha512-jJ0bqzaylmJtVnNgzTeSOs8DPavpbYgEr/b0YL8/2GO3xJEhInFmhKMUnEJQjZumK7KXGFhUy89PrsJWlakBVg==";
  };
  "commander@14.0.2" = fetchurl {
    url = "https://registry.npmjs.org/commander/-/commander-14.0.2.tgz";
    hash = "sha512-TywoWNNRbhoD0BXs1P3ZEScW8W5iKrnbithIl0YH+uCmBd0QpPOA8yc82DS3BIE5Ma6FnBVUsJ7wVUDz4dvOWQ==";
  };
  "decompress-response@6.0.0" = fetchurl {
    url = "https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz";
    hash = "sha512-aW35yZM6Bb/4oJlZncMH2LCoZtJXTRxES17vE3hoRiowU2kWHaJKFkSBDnDR+cm9J+9QhXmREyIfv0pji9ejCQ==";
  };
  "deep-extend@0.6.0" = fetchurl {
    url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz";
    hash = "sha512-LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
  };
  "detect-libc@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/detect-libc/-/detect-libc-2.1.2.tgz";
    hash = "sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==";
  };
  "end-of-stream@1.4.5" = fetchurl {
    url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.5.tgz";
    hash = "sha512-ooEGc6HP26xXq/N+GCGOT0JKCLDGrq2bQUZrQ7gyrJiZANJ/8YDTxTpQBXGMn+WbIQXNVpyWymm7KYVICQnyOg==";
  };
  "expand-template@2.0.3" = fetchurl {
    url = "https://registry.npmjs.org/expand-template/-/expand-template-2.0.3.tgz";
    hash = "sha512-XYfuKMvj4O35f/pOXLObndIRvyQ+/+6AhODh+OKWj9S9498pHHn/IMszH+gt0fBCRWMNfk1ZSp5x3AifmnI2vg==";
  };
  "fs-constants@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/fs-constants/-/fs-constants-1.0.0.tgz";
    hash = "sha512-y6OAwoSIf7FyjMIv94u+b5rdheZEjzR63GTyZJm5qh4Bi+2YgwLCcI/fPFZkL5PSixOt6ZNKm+w+Hfp/Bciwow==";
  };
  "gifenc@1.0.3" = fetchurl {
    url = "https://registry.npmjs.org/gifenc/-/gifenc-1.0.3.tgz";
    hash = "sha512-xdr6AdrfGBcfzncONUOlXMBuc5wJDtOueE3c5rdG0oNgtINLD+f2iFZltrBRZYzACRbKr+mSVU/x98zv2u3jmw==";
  };
  "github-from-package@0.0.0" = fetchurl {
    url = "https://registry.npmjs.org/github-from-package/-/github-from-package-0.0.0.tgz";
    hash = "sha512-SyHy3T1v2NUXn29OsWdxmK6RwHD+vkj3v8en8AOBZ1wBQ/hCAQ5bAQTD02kW4W9tUp/3Qh6J8r9EvntiyCmOOw==";
  };
  "hachure-fill@0.5.2" = fetchurl {
    url = "https://registry.npmjs.org/hachure-fill/-/hachure-fill-0.5.2.tgz";
    hash = "sha512-3GKBOn+m2LX9iq+JC1064cSFprJY4jL1jCXTcpnfER5HYE2l/4EfWSGzkPa/ZDBmYI0ZOEj5VHV/eKnPGkHuOg==";
  };
  "ieee754@1.2.1" = fetchurl {
    url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
    hash = "sha512-dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
  };
  "image-size@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/image-size/-/image-size-2.0.2.tgz";
    hash = "sha512-IRqXKlaXwgSMAMtpNzZa1ZAe8m+Sa1770Dhk8VkSsP9LS+iHD62Zd8FQKs8fbPiagBE7BzoFX23cxFnwshpV6w==";
  };
  "inherits@2.0.4" = fetchurl {
    url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
    hash = "sha512-k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
  };
  "ini@1.3.8" = fetchurl {
    url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
    hash = "sha512-JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
  };
  "mimic-response@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz";
    hash = "sha512-z0yWI+4FDrrweS8Zmt4Ej5HdJmky15+L2e6Wgn3+iK5fWzb6T3fhNFq2+MeTRb064c6Wr4N/wv0DzQTjNzHNGQ==";
  };
  "minimist@1.2.8" = fetchurl {
    url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
    hash = "sha512-2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
  };
  "mkdirp-classic@0.5.3" = fetchurl {
    url = "https://registry.npmjs.org/mkdirp-classic/-/mkdirp-classic-0.5.3.tgz";
    hash = "sha512-gKLcREMhtuZRwRAfqP3RFW+TK4JqApVBtOIftVgjuABpAtpxhPGaDcfvbhNvD0B8iD1oUr/txX35NjcaY6Ns/A==";
  };
  "napi-build-utils@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/napi-build-utils/-/napi-build-utils-2.0.0.tgz";
    hash = "sha512-GEbrYkbfF7MoNaoh2iGG84Mnf/WZfB0GdGEsM8wz7Expx/LlWf5U8t9nvJKXSp3qr5IsEbK04cBGhol/KwOsWA==";
  };
  "node-abi@3.87.0" = fetchurl {
    url = "https://registry.npmjs.org/node-abi/-/node-abi-3.87.0.tgz";
    hash = "sha512-+CGM1L1CgmtheLcBuleyYOn7NWPVu0s0EJH2C4puxgEZb9h8QpR9G2dBfZJOAUhi7VQxuBPMd0hiISWcTyiYyQ==";
  };
  "node-addon-api@7.1.1" = fetchurl {
    url = "https://registry.npmjs.org/node-addon-api/-/node-addon-api-7.1.1.tgz";
    hash = "sha512-5m3bsyrjFWE1xf7nz7YXdN4udnVtXK6/Yfgn5qnahL6bCkf2yKt4k3nuTKAtT4r3IG8JNR2ncsIMdZuAzJjHQQ==";
  };
  "omggif@1.0.10" = fetchurl {
    url = "https://registry.npmjs.org/omggif/-/omggif-1.0.10.tgz";
    hash = "sha512-LMJTtvgc/nugXj0Vcrrs68Mn2D1r0zf630VNtqtpI1FEO7e+O9FP4gqs9AcnBaSEeoHIPm28u6qgPR0oyEpGSw==";
  };
  "once@1.4.0" = fetchurl {
    url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
    hash = "sha512-lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
  };
  "path-data-parser@0.1.0" = fetchurl {
    url = "https://registry.npmjs.org/path-data-parser/-/path-data-parser-0.1.0.tgz";
    hash = "sha512-NOnmBpt5Y2RWbuv0LMzsayp3lVylAHLPUTut412ZA3l+C4uw4ZVkQbjShYCQ8TCpUMdPapr4YjUqLYD6v68j+w==";
  };
  "perfect-freehand@1.2.2" = fetchurl {
    url = "https://registry.npmjs.org/perfect-freehand/-/perfect-freehand-1.2.2.tgz";
    hash = "sha512-eh31l019WICQ03pkF3FSzHxB8n07ItqIQ++G5UV8JX0zVOXzgTGCqnRR0jJ2h9U8/2uW4W4mtGJELt9kEV0CFQ==";
  };
  "pixelmatch@7.1.0" = fetchurl {
    url = "https://registry.npmjs.org/pixelmatch/-/pixelmatch-7.1.0.tgz";
    hash = "sha512-1wrVzJ2STrpmONHKBy228LM1b84msXDUoAzVEl0R8Mz4Ce6EPr+IVtxm8+yvrqLYMHswREkjYFaMxnyGnaY3Ng==";
  };
  "pngjs@7.0.0" = fetchurl {
    url = "https://registry.npmjs.org/pngjs/-/pngjs-7.0.0.tgz";
    hash = "sha512-LKWqWJRhstyYo9pGvgor/ivk2w94eSjE3RGVuzLGlr3NmD8bf7RcYGze1mNdEHRP6TRP6rMuDHk5t44hnTRyow==";
  };
  "points-on-curve@0.2.0" = fetchurl {
    url = "https://registry.npmjs.org/points-on-curve/-/points-on-curve-0.2.0.tgz";
    hash = "sha512-0mYKnYYe9ZcqMCWhUjItv/oHjvgEsfKvnUTg8sAtnHr3GVy7rGkXCb6d5cSyqrWqL4k81b9CPg3urd+T7aop3A==";
  };
  "points-on-curve@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/points-on-curve/-/points-on-curve-1.0.1.tgz";
    hash = "sha512-3nmX4/LIiyuwGLwuUrfhTlDeQFlAhi7lyK/zcRNGhalwapDWgAGR82bUpmn2mA03vII3fvNCG8jAONzKXwpxAg==";
  };
  "points-on-path@0.2.1" = fetchurl {
    url = "https://registry.npmjs.org/points-on-path/-/points-on-path-0.2.1.tgz";
    hash = "sha512-25ClnWWuw7JbWZcgqY/gJ4FQWadKxGWk+3kR/7kD0tCaDtPPMj7oHu2ToLaVhfpnHrZzYby2w6tUA0eOIuUg8g==";
  };
  "prebuild-install@7.1.3" = fetchurl {
    url = "https://registry.npmjs.org/prebuild-install/-/prebuild-install-7.1.3.tgz";
    hash = "sha512-8Mf2cbV7x1cXPUILADGI3wuhfqWvtiLA1iclTDbFRZkgRQS0NqsPZphna9V+HyTEadheuPmjaJMsbzKQFOzLug==";
  };
  "pump@3.0.3" = fetchurl {
    url = "https://registry.npmjs.org/pump/-/pump-3.0.3.tgz";
    hash = "sha512-todwxLMY7/heScKmntwQG8CXVkWUOdYxIvY2s0VWAAMh/nd8SoYiRaKjlr7+iCs984f2P8zvrfWcDDYVb73NfA==";
  };
  "rc@1.2.8" = fetchurl {
    url = "https://registry.npmjs.org/rc/-/rc-1.2.8.tgz";
    hash = "sha512-y3bGgqKj3QBdxLbLkomlohkvsA8gdAiUQlSBJnBhfn+BPxg4bc62d8TcBW15wavDfgexCgccckhcZvywyQYPOw==";
  };
  "readable-stream@3.6.2" = fetchurl {
    url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.2.tgz";
    hash = "sha512-9u/sniCrY3D5WdsERHzHE4G2YCXqoG5FTHUiCC4SIbr6XcLZBY05ya9EKjYek9O5xOAwjGq+1JdGBAS7Q9ScoA==";
  };
  "roughjs@4.6.6" = fetchurl {
    url = "https://registry.npmjs.org/roughjs/-/roughjs-4.6.6.tgz";
    hash = "sha512-ZUz/69+SYpFN/g/lUlo2FXcIjRkSu3nDarreVdGGndHEBJ6cXPdKguS8JGxwj5HA5xIbVKSmLgr5b3AWxtRfvQ==";
  };
  "safe-buffer@5.2.1" = fetchurl {
    url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
    hash = "sha512-rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
  };
  "semver@7.7.3" = fetchurl {
    url = "https://registry.npmjs.org/semver/-/semver-7.7.3.tgz";
    hash = "sha512-SdsKMrI9TdgjdweUSR9MweHA4EJ8YxHn8DFaDisvhVlUOe4BF1tLD7GAj0lIqWVl+dPb/rExr0Btby5loQm20Q==";
  };
  "simple-concat@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.1.tgz";
    hash = "sha512-cSFtAPtRhljv69IK0hTVZQ+OfE9nePi/rtJmw5UjHeVyVroEqJXP1sFztKUy1qU+xvz3u/sfYJLa947b7nAN2Q==";
  };
  "simple-get@4.0.1" = fetchurl {
    url = "https://registry.npmjs.org/simple-get/-/simple-get-4.0.1.tgz";
    hash = "sha512-brv7p5WgH0jmQJr1ZDDfKDOSeWWg+OVypG99A/5vYGPqJ6pxiaHLy8nxtFjBA7oMa01ebA9gfh1uMCFqOuXxvA==";
  };
  "string_decoder@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
    hash = "sha512-hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
  };
  "strip-json-comments@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz";
    hash = "sha512-4gB8na07fecVVkOI6Rs4e7T6NOTki5EmL7TUduTs6bu3EdnSycntVJ4re8kgZA+wx9IueI2Y11bfbgwtzuE0KQ==";
  };
  "tar-fs@2.1.4" = fetchurl {
    url = "https://registry.npmjs.org/tar-fs/-/tar-fs-2.1.4.tgz";
    hash = "sha512-mDAjwmZdh7LTT6pNleZ05Yt65HC3E+NiQzl672vQG38jIrehtJk/J3mNwIg+vShQPcLF/LV7CMnDW6vjj6sfYQ==";
  };
  "tar-stream@2.2.0" = fetchurl {
    url = "https://registry.npmjs.org/tar-stream/-/tar-stream-2.2.0.tgz";
    hash = "sha512-ujeqbceABgwMZxEJnk2HDY2DlnUZ+9oEcb1KzTVfYHio0UE6dG71n60d8D2I4qNvleWrrXpmjpt7vZeF1LnMZQ==";
  };
  "tunnel-agent@0.6.0" = fetchurl {
    url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
    hash = "sha512-McnNiV1l8RYeY8tBgEpuodCC1mLUdbSN+CYBL7kJsJNInOP8UjDDEwdk6Mw60vdLLrr5NHKZhMAOSrR2NZuQ+w==";
  };
  "typescript@5.9.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
    hash = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
  };
  "undici-types@7.16.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.16.0.tgz";
    hash = "sha512-Zz+aZWSj8LE6zoxD+xrjh4VfkIG8Ya6LvYkZqtUQGJPZjYl53ypCaUwWqo7eI0x66KBGeRo+mlBEkMSeSZ38Nw==";
  };
  "util-deprecate@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
    hash = "sha512-EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
  };
  "wawoff2@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/wawoff2/-/wawoff2-2.0.1.tgz";
    hash = "sha512-r0CEmvpH63r4T15ebFqeOjGqU4+EgTx4I510NtK35EMciSdcTxCw3Byy3JnBonz7iyIFZ0AbVo0bbFpEVuhCYA==";
  };
  "wrappy@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
    hash = "sha512-l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
  };
}
